//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CustomLangParser.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CustomLanguage.Grammar {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CustomLangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public interface ICustomLangParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] CustomLangParser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] CustomLangParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc([NotNull] CustomLangParser.FuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParams([NotNull] CustomLangParser.ParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] CustomLangParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] CustomLangParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CustomLangParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.letStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetStatement([NotNull] CustomLangParser.LetStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] CustomLangParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStatement([NotNull] CustomLangParser.ElseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] CustomLangParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject([NotNull] CustomLangParser.ObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.objectHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectHead([NotNull] CustomLangParser.ObjectHeadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.usesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsesStatement([NotNull] CustomLangParser.UsesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.useList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseList([NotNull] CustomLangParser.UseListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.singleUse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleUse([NotNull] CustomLangParser.SingleUseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.useBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseBlock([NotNull] CustomLangParser.UseBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.useSequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseSequence([NotNull] CustomLangParser.UseSequenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.objectBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectBody([NotNull] CustomLangParser.ObjectBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.objectField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectField([NotNull] CustomLangParser.ObjectFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModifier([NotNull] CustomLangParser.ModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameters([NotNull] CustomLangParser.ParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.parameterDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDecl([NotNull] CustomLangParser.ParameterDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] CustomLangParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] CustomLangParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.callExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallExpression([NotNull] CustomLangParser.CallExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] CustomLangParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.primaryExpressionNonParen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpressionNonParen([NotNull] CustomLangParser.PrimaryExpressionNonParenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] CustomLangParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] CustomLangParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] CustomLangParser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] CustomLangParser.RelationalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAndExpression([NotNull] CustomLangParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOrExpression([NotNull] CustomLangParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CustomLangParser.ExpressionContext context);
}
} // namespace CustomLanguage.Grammar
