//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CustomLangParser.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CustomLanguage.Grammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICustomLangParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class CustomLangParserBaseListener : ICustomLangParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterId([NotNull] CustomLangParser.IdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitId([NotNull] CustomLangParser.IdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] CustomLangParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] CustomLangParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc([NotNull] CustomLangParser.FuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc([NotNull] CustomLangParser.FuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParams([NotNull] CustomLangParser.ParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParams([NotNull] CustomLangParser.ParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] CustomLangParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] CustomLangParser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] CustomLangParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] CustomLangParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] CustomLangParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] CustomLangParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.letStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLetStatement([NotNull] CustomLangParser.LetStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.letStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLetStatement([NotNull] CustomLangParser.LetStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] CustomLangParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] CustomLangParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStatement([NotNull] CustomLangParser.ElseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStatement([NotNull] CustomLangParser.ElseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] CustomLangParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] CustomLangParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject([NotNull] CustomLangParser.ObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject([NotNull] CustomLangParser.ObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.objectHead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectHead([NotNull] CustomLangParser.ObjectHeadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.objectHead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectHead([NotNull] CustomLangParser.ObjectHeadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.usesStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsesStatement([NotNull] CustomLangParser.UsesStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.usesStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsesStatement([NotNull] CustomLangParser.UsesStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.useList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUseList([NotNull] CustomLangParser.UseListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.useList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUseList([NotNull] CustomLangParser.UseListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.singleUse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleUse([NotNull] CustomLangParser.SingleUseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.singleUse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleUse([NotNull] CustomLangParser.SingleUseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.useBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUseBlock([NotNull] CustomLangParser.UseBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.useBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUseBlock([NotNull] CustomLangParser.UseBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.useSequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUseSequence([NotNull] CustomLangParser.UseSequenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.useSequence"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUseSequence([NotNull] CustomLangParser.UseSequenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.objectBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectBody([NotNull] CustomLangParser.ObjectBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.objectBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectBody([NotNull] CustomLangParser.ObjectBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.objectField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectField([NotNull] CustomLangParser.ObjectFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.objectField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectField([NotNull] CustomLangParser.ObjectFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifier([NotNull] CustomLangParser.ModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifier([NotNull] CustomLangParser.ModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters([NotNull] CustomLangParser.ParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters([NotNull] CustomLangParser.ParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.parameterDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterDecl([NotNull] CustomLangParser.ParameterDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.parameterDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterDecl([NotNull] CustomLangParser.ParameterDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] CustomLangParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] CustomLangParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgs([NotNull] CustomLangParser.ArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgs([NotNull] CustomLangParser.ArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.callExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallExpression([NotNull] CustomLangParser.CallExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.callExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallExpression([NotNull] CustomLangParser.CallExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] CustomLangParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] CustomLangParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.primaryExpressionNonParen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpressionNonParen([NotNull] CustomLangParser.PrimaryExpressionNonParenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.primaryExpressionNonParen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpressionNonParen([NotNull] CustomLangParser.PrimaryExpressionNonParenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpression([NotNull] CustomLangParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpression([NotNull] CustomLangParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpression([NotNull] CustomLangParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpression([NotNull] CustomLangParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpression([NotNull] CustomLangParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpression([NotNull] CustomLangParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] CustomLangParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] CustomLangParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.logicalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalAndExpression([NotNull] CustomLangParser.LogicalAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.logicalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalAndExpression([NotNull] CustomLangParser.LogicalAndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.logicalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOrExpression([NotNull] CustomLangParser.LogicalOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.logicalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOrExpression([NotNull] CustomLangParser.LogicalOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] CustomLangParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] CustomLangParser.ExpressionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace CustomLanguage.Grammar
