//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CustomLangParser.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CustomLanguage.Grammar {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CustomLangParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public interface ICustomLangParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId([NotNull] CustomLangParser.IdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId([NotNull] CustomLangParser.IdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] CustomLangParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] CustomLangParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc([NotNull] CustomLangParser.FuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc([NotNull] CustomLangParser.FuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParams([NotNull] CustomLangParser.ParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParams([NotNull] CustomLangParser.ParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] CustomLangParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] CustomLangParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] CustomLangParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] CustomLangParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CustomLangParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CustomLangParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.letStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetStatement([NotNull] CustomLangParser.LetStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.letStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetStatement([NotNull] CustomLangParser.LetStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] CustomLangParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] CustomLangParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStatement([NotNull] CustomLangParser.ElseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStatement([NotNull] CustomLangParser.ElseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] CustomLangParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] CustomLangParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] CustomLangParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] CustomLangParser.ObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.objectHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectHead([NotNull] CustomLangParser.ObjectHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.objectHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectHead([NotNull] CustomLangParser.ObjectHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.usesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsesStatement([NotNull] CustomLangParser.UsesStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.usesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsesStatement([NotNull] CustomLangParser.UsesStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.useList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUseList([NotNull] CustomLangParser.UseListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.useList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUseList([NotNull] CustomLangParser.UseListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.singleUse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleUse([NotNull] CustomLangParser.SingleUseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.singleUse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleUse([NotNull] CustomLangParser.SingleUseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.useBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUseBlock([NotNull] CustomLangParser.UseBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.useBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUseBlock([NotNull] CustomLangParser.UseBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.useSequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUseSequence([NotNull] CustomLangParser.UseSequenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.useSequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUseSequence([NotNull] CustomLangParser.UseSequenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.objectBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectBody([NotNull] CustomLangParser.ObjectBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.objectBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectBody([NotNull] CustomLangParser.ObjectBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.objectField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectField([NotNull] CustomLangParser.ObjectFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.objectField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectField([NotNull] CustomLangParser.ObjectFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifier([NotNull] CustomLangParser.ModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifier([NotNull] CustomLangParser.ModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] CustomLangParser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] CustomLangParser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.parameterDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterDecl([NotNull] CustomLangParser.ParameterDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.parameterDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterDecl([NotNull] CustomLangParser.ParameterDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] CustomLangParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] CustomLangParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([NotNull] CustomLangParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([NotNull] CustomLangParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.callExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallExpression([NotNull] CustomLangParser.CallExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.callExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallExpression([NotNull] CustomLangParser.CallExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] CustomLangParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] CustomLangParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.primaryExpressionNonParen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpressionNonParen([NotNull] CustomLangParser.PrimaryExpressionNonParenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.primaryExpressionNonParen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpressionNonParen([NotNull] CustomLangParser.PrimaryExpressionNonParenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] CustomLangParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] CustomLangParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] CustomLangParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] CustomLangParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] CustomLangParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] CustomLangParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] CustomLangParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] CustomLangParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpression([NotNull] CustomLangParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpression([NotNull] CustomLangParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpression([NotNull] CustomLangParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpression([NotNull] CustomLangParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CustomLangParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CustomLangParser.ExpressionContext context);
}
} // namespace CustomLanguage.Grammar
